POST http://localhost:3333/sys/setup HTTP/1.1
content-type: application/json

{
  "key": "shekhar83#"
}

###

GET http://localhost:3333/api/crud/select/query?sql=SELECT * FROM party;

###

POST http://localhost:3333/api/crud/create/party 
content-type: application/json 

{
  "address": "S-9, Vivek Apartments, Shrestha Vihar",
  "balamt": "25",
  "baldate": "2022/03/26",
  "baltype": "Pay",
  "comments": "",
  "contact": "9910075648",
  "credit": 25,
  "debit": 0,
  "email": "rshekhar21@gmail.com",
  "name": "Raj Shekhar Singh",
  "pan": "",
  "party": "n_xY66",
  "ptype": "Contractor",
  "refby": "",
  "regdate": "2022/03/26"
}

###
GET http://localhost:3333/api/crud/select/party 
###

POST http://localhost:3333/api/crud/update/party 
content-type: application/json 

{
  "address": "",
  "balamt": "2500",
  "baldate": "2022/03/26",
  "baltype": "Receive",
  "comments": "",
  "contact": "9910099100",
  "credit": 2500,
  "debit": 0,
  "email": "shekhar@gmail.com",
  "id": 2,
  "name": "shekhar",
  "pan": "BKLPS9633P",
  "party": "c_koA9",
  "ptype": "Customer",
  "refby": "rajesh",
  "regdate": "2022/03/26"
}


###
GET http://localhost:3333/api/crud/select/query?sql=select concat(fullname, ' /', party) as name from party order by fullname asc

###

GET http://localhost:3333/api/crud/select/query?sql=select * from daybook


###

POST http://localhost:3333/api/crud/create/daybook 
content-type: application/json 

{
  "amtpaid": 2500,
  "comments": "paid for test",
  "edate": "2022/03/26",
  "name": "mahesh",
  "party": "n_rbso",
  "pmode": "cash",
  "received": 0
}

###

POST http://localhost:3333/api/crud/update/daybook
content-type: application/json 

{    
  "pmode": "online",
  "comments": "abcd",
  "name": "raj singh",
  "edate": "2022/3/21", 
  "amtpaid": 2500,
  "received": 0,
  "party": "n_rbso",
  "id": 4
}

###
GET http://localhost:3333/api/crud/select/query?sql=select id, party, fullname, to_char(entry_date, 'DD/MM/YYYY'), amt_paid, amt_received, pymt_mode, narraction commetns from daybook where entry_date = '2022/03/01' order by entry_date desc;
